module.exports = {
    login: 'NoeCR',
    id: 35569564,
    node_id: 'MDQ6VXNlcjM1NTY5NTY0',
    avatar_url: 'https://avatars1.githubusercontent.com/u/35569564?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/NoeCR',
    html_url: 'https://github.com/NoeCR',
    followers_url: 'https://api.github.com/users/NoeCR/followers',
    following_url: 'https://api.github.com/users/NoeCR/following{/other_user}',
    gists_url: 'https://api.github.com/users/NoeCR/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/NoeCR/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/NoeCR/subscriptions',
    organizations_url: 'https://api.github.com/users/NoeCR/orgs',
    repos_url: 'https://api.github.com/users/NoeCR/repos',
    events_url: 'https://api.github.com/users/NoeCR/events{/privacy}',
    received_events_url: 'https://api.github.com/users/NoeCR/received_events',
    type: 'User',
    site_admin: false,
    name: 'Noé',
    company: 'Bit2Me',
    blog: '',
    location: 'Castellón',
    email: null,
    hireable: true,
    bio: 'Web Developer',
    public_repos: 36,
    public_gists: 0,
    followers: 5,
    following: 46,
    created_at: '2018-01-18T14:49:00Z',
    updated_at: '2019-12-30T11:21:50Z'
};